# Generated by Django 4.2.16 on 2024-09-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_email_client_first_name_client_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='preferences',
            field=models.TextField(blank=True),
        ),
    ]
