# Generated by Django 4.2.16 on 2024-09-20 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('consultation_date', models.DateField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('estimated_total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('service', models.ManyToManyField(to='services.service')),
            ],
        ),
    ]
